Weapon machines
vincetiu8/zombie-game pull request #260
Opened 2021-12-03 03:32 UTC by RKSDude

Not done

2021-12-06 08:12 UTC, BryceLao approved these changes
LGTM

2021-12-06 09:33 UTC, vincetiu8 commented on Assets/Scripts/PlayerScripts/WeaponsHandler.cs
> +			selectedIndex = (selectedIndex + availableWeapons.Count) % availableWeapons.Count;
Shouldn't there be a -1 somewhere? Idk

2021-12-06 09:36 UTC, vincetiu8 requested changes
I'm still getting issues with multiple weapons being out at once.

![Screenshot from 2021-12-06 17-35-54](https://user-images.githubusercontent.com/46623413/144822597-86e83813-7211-47cd-a7c5-d65e3f1223ac.png)

Also I get null reference errors when I try to interact with the machine.
![Screenshot from 2021-12-06 17-36-43](https://user-images.githubusercontent.com/46623413/144822698-b4368aa0-336d-4dd4-a103-0770c5802b9a.png)

2021-12-06 09:36 UTC, vincetiu8 commented on Assets/Scripts/Weapons/WeaponPickup.cs
> +		private Vector3        _offset = new Vector3(0.4f, -0.55f, 0);
Need to set this for all guns now. Should be serialized.

2022-01-20 03:35 UTC, vincetiu8 requested changes
The shops are broken: buying an item makes the player freeze and triggers a nullreference exception.

2022-02-06 05:39 UTC, vincetiu8 approved these changes
LGTM but I worked on this so I'd like someone else to approve too before merging.

2022-02-07 08:24 UTC, merged